#############################################################################
# Makefile for building: application
# Generated by qmake (2.01a) (Qt 4.8.6) on: Thu Aug 27 19:34:58 2015
# Project:  application.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile application.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I. -I/usr/local/include/opencv -I/usr/local/include -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/usr/local/lib -lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_gpu -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_nonfree -lopencv_objdetect -lopencv_ocl -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_ts -lopencv_video -lopencv_videostab -lopencv_viz -ltbb -lXext -lX11 -lICE -lSM -lGL -lGLU -lrt -lm -ldl -lQtWebKit -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = assistant.cpp \
		dialogs.cpp \
		edge.cpp \
		enhancement.cpp \
		helpwindow.cpp \
		histwindow.cpp \
		main.cpp \
		mainwindow.cpp \
		thresholding.cpp \
		subwindow.cpp moc_dialogs.cpp \
		moc_helpwindow.cpp \
		moc_histwindow.cpp \
		moc_mainwindow.cpp \
		moc_subwindow.cpp \
		qrc_application.cpp
OBJECTS       = assistant.o \
		dialogs.o \
		edge.o \
		enhancement.o \
		helpwindow.o \
		histwindow.o \
		main.o \
		mainwindow.o \
		thresholding.o \
		subwindow.o \
		moc_dialogs.o \
		moc_helpwindow.o \
		moc_histwindow.o \
		moc_mainwindow.o \
		moc_subwindow.o \
		qrc_application.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		application.pro
QMAKE_TARGET  = application
DESTDIR       = 
TARGET        = application

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: application.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtWebKit.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile application.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtWebKit.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile application.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/application1.0.0 || $(MKDIR) .tmp/application1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/application1.0.0/ && $(COPY_FILE) --parents assistant.h dialogs.h edge.h enhancement.h helpwindow.h histwindow.h mainwindow.h thresholding.h imageconverter.h subwindow.h .tmp/application1.0.0/ && $(COPY_FILE) --parents application.qrc .tmp/application1.0.0/ && $(COPY_FILE) --parents assistant.cpp dialogs.cpp edge.cpp enhancement.cpp helpwindow.cpp histwindow.cpp main.cpp mainwindow.cpp thresholding.cpp subwindow.cpp .tmp/application1.0.0/ && (cd `dirname .tmp/application1.0.0` && $(TAR) application1.0.0.tar application1.0.0 && $(COMPRESS) application1.0.0.tar) && $(MOVE) `dirname .tmp/application1.0.0`/application1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/application1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_dialogs.cpp moc_helpwindow.cpp moc_histwindow.cpp moc_mainwindow.cpp moc_subwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dialogs.cpp moc_helpwindow.cpp moc_histwindow.cpp moc_mainwindow.cpp moc_subwindow.cpp
moc_dialogs.cpp: assistant.h \
		mainwindow.h \
		helpwindow.h \
		imageconverter.h \
		dialogs.h \
		subwindow.h \
		histwindow.h \
		enhancement.h \
		edge.h \
		thresholding.h \
		dialogs.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) dialogs.h -o moc_dialogs.cpp

moc_helpwindow.cpp: helpwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) helpwindow.h -o moc_helpwindow.cpp

moc_histwindow.cpp: mainwindow.h \
		helpwindow.h \
		imageconverter.h \
		dialogs.h \
		assistant.h \
		subwindow.h \
		histwindow.h \
		enhancement.h \
		edge.h \
		thresholding.h \
		histwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) histwindow.h -o moc_histwindow.cpp

moc_mainwindow.cpp: helpwindow.h \
		imageconverter.h \
		dialogs.h \
		assistant.h \
		mainwindow.h \
		histwindow.h \
		subwindow.h \
		enhancement.h \
		edge.h \
		thresholding.h \
		mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_subwindow.cpp: helpwindow.h \
		imageconverter.h \
		dialogs.h \
		assistant.h \
		mainwindow.h \
		histwindow.h \
		subwindow.h \
		enhancement.h \
		edge.h \
		thresholding.h \
		subwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) subwindow.h -o moc_subwindow.cpp

compiler_rcc_make_all: qrc_application.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_application.cpp
qrc_application.cpp: application.qrc \
		images/zoom_best_fit.png \
		images/copy.png \
		images/cut.png \
		images/save.png \
		images/zoom_out.png \
		images/paste.png \
		images/histogram.png \
		images/open.png \
		images/zoom_in.png
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name application application.qrc -o qrc_application.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

assistant.o: assistant.cpp assistant.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o assistant.o assistant.cpp

dialogs.o: dialogs.cpp dialogs.h \
		assistant.h \
		mainwindow.h \
		helpwindow.h \
		imageconverter.h \
		histwindow.h \
		subwindow.h \
		enhancement.h \
		edge.h \
		thresholding.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialogs.o dialogs.cpp

edge.o: edge.cpp edge.h \
		assistant.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o edge.o edge.cpp

enhancement.o: enhancement.cpp enhancement.h \
		assistant.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o enhancement.o enhancement.cpp

helpwindow.o: helpwindow.cpp helpwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o helpwindow.o helpwindow.cpp

histwindow.o: histwindow.cpp histwindow.h \
		mainwindow.h \
		helpwindow.h \
		imageconverter.h \
		dialogs.h \
		assistant.h \
		subwindow.h \
		enhancement.h \
		edge.h \
		thresholding.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o histwindow.o histwindow.cpp

main.o: main.cpp mainwindow.h \
		helpwindow.h \
		imageconverter.h \
		dialogs.h \
		assistant.h \
		subwindow.h \
		histwindow.h \
		enhancement.h \
		edge.h \
		thresholding.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		helpwindow.h \
		imageconverter.h \
		dialogs.h \
		assistant.h \
		subwindow.h \
		histwindow.h \
		enhancement.h \
		edge.h \
		thresholding.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

thresholding.o: thresholding.cpp thresholding.h \
		assistant.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o thresholding.o thresholding.cpp

subwindow.o: subwindow.cpp subwindow.h \
		helpwindow.h \
		imageconverter.h \
		dialogs.h \
		assistant.h \
		mainwindow.h \
		histwindow.h \
		enhancement.h \
		edge.h \
		thresholding.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o subwindow.o subwindow.cpp

moc_dialogs.o: moc_dialogs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialogs.o moc_dialogs.cpp

moc_helpwindow.o: moc_helpwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_helpwindow.o moc_helpwindow.cpp

moc_histwindow.o: moc_histwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_histwindow.o moc_histwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_subwindow.o: moc_subwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_subwindow.o moc_subwindow.cpp

qrc_application.o: qrc_application.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_application.o qrc_application.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

